[os.symbols]
AIX = ""
AlmaLinux = ""
Alpaquita = ""
Alpine = ""
ALTLinux = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = ""
Artix = ""
Bluefin = ""
CachyOS = ""
CentOS = ""
Debian = ""
DragonFly = ""
Elementary = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = ""
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = ""
InstantOS = ""
Ios = "󰀷"
Kali = ""
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
Nobara = ""
OpenBSD = ""
OpenCloudOS = ""
openEuler = ""
openSUSE = ""
OracleLinux = "󰺡"
PikaOS = ""
Pop = ""
Raspbian = ""
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Redox = "󰀘"
RockyLinux = ""
Solus = ""
SUSE = ""
Ubuntu = ""
Ultramarine = ""
Unknown = ""
Uos = ""
Void = ""
Windows = "󰍲"
Zorin = ""
